### ISSUE TITLE
The upload file is throwing an bad request

### ISSUE THREAD

**Issue by aspx** [gphotosuploader/google-photos-api-client-go#53]
Hi , 

I need some help from you guys, probably this is not a bug and and I'm doing something wrong, but I'm getting always bad request when trying to upload an photo.  

I've investigate a bit the code and something raise my attention. In bellow function we are putting `nil` on body request, is this the expected value or should it be the return of `item.Open()`  ? 

```
func (u BasicUploader) prepareUploadRequest(item uploader.UploadItem) (*http.Request, error) {
	_, size, err := item.Open()
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", u.url, nil)
```

**Describe the bug**

The upload file is throwing an bad request (http 400)

**To Reproduce**

Sample code for basic upload:

```
...

srv, err := gphotos.NewClient(client)

...

s, err := srv.Uploader.UploadFile(ctx, "img1.jpg")

```

I'm receiving the following error: 

got 400 Bad Request: {
  "code": 3,
  "message": "Payload must not be empty"
}

**Expected behavior**

Get the upload token if the photo was successful uploaded.

**Comment by pacoorozco** [comment]
Yes, you're right. The basic uploader is not working and the test is not raising any problem 🙃

You can use the resumable uploader or if you prefer it, the [gphotos-uploader-cli](https://github.com/gphotosuploader/gphotos-uploader-cli)

**Comment by aspx** [comment]
Hi,

Thanks for your input 🙂

I've already solved locally the issue, should I do a pull request or you will take care ? 

Thanks so much 💪

**Comment by pacoorozco** [comment]
Hi

Feel free to do a PR, but please include a test to avoid this happening again. 

Thanks
