### ISSUE TITLE
Method to list MediaItems in an Album with pagination

### ISSUE THREAD

**Issue by jasondborneman** [gphotosuploader/google-photos-api-client-go#65]
**Describe the bug**
Currently it seems that MediaItems.ListByAlbums only returns the first page of results. For albums with more photos, only the latest 25 are returned in the []mediaItems slice.

**To Reproduce**
```
        gpc, err := gphotos.NewClient(client)
        ta, err := gpc.Albums.GetById(ctx, "<AlbumId>")
        if err != nil {
                log.Fatal(err)
        }
        taid := ta.ID
        log.Println("Album Count is: " + ta.MediaItemsCount)
        mic,err := strconv.Atoi(ta.MediaItemsCount)
        if err != nil {
                log.Fatal(err)
        }
        cmi := rand.Intn(mic - 1)
        log.Println("Chosen Media Index is: " + strconv.Itoa(cmi))

        am, err := gpc.MediaItems.ListByAlbum(ctx, taid)
        log.Println("Number of Media Items Returned is: " + strconv.Itoa(len(am)))
```
Output:
```
2022/01/04 09:36:45 Album Count is: 11558
2022/01/04 09:36:45 Chosen Media Index is: 11346
2022/01/04 09:36:46 Number of Media Items Returned is: 25
```

**Expected behavior**
Paging should be supported so that all media items can be retrieved.

**Additional context**
I'm writing a go program that will randomly choose a photo from a given (large) album.

**Comment by jasondborneman** [comment]
Sorry in advance if this should be a feature. Thought of that AFTER I hit submit, naturally. :|

**Comment by pacoorozco** [comment]
It seems a bug @jasondborneman Let me see if it can be fixed easily...

**Comment by pacoorozco** [comment]
Hi @jasondborneman 

Can you test the `v2.3.1-alpha` in the `main` branch?

I'll wait until your confirmation before publishing the final v2.3.1.

**Comment by jasondborneman** [comment]
@pacoorozco I'm trying it now, but the MediaItems.ListByAlbum took ~5 minutes. I haven't looked at your PR yet, but I'm assuming you've got it going through the pages and just returning everything? For really large albums it might be better to support the paging through the module than just return eveyrthing (if my assumption about it is correct)

Here's my script output with your fix. See the timestamps.

```
2022/01/08 21:29:00 Album Name is: Tidbyt
2022/01/08 21:29:00 Album Count is: 11572
2022/01/08 21:29:00 Chosen Media Index is: 461
2022/01/08 21:34:10 Number of Media Items Returned is: 11572
```

**Comment by jasondborneman** [comment]
That might mean interface changes to your functions though, so I understand if that's not necessarily an undertaking you'd like to take at this time. I admittedly have a very large album that is probably a bit of an edge case scenario 😬

**Comment by pacoorozco** [comment]
Hi @jasondborneman 

In the beginning I was implementing higher level calls wrapping the `github.com/gphotosuploader/googlemirror/api/photoslibrary/v1` library. These higher level calls were implemented in a way that reduce the complexity of the library. 

The `github.com/gphotosuploader/googlemirror/api/photoslibrary/v1` library has already a call for listing the items inside the album (see [SearchMediaItemsRequest](https://github.com/gphotosuploader/googlemirror/blob/a2e0a842a693bad6221a0c10a8845be8ba99725f/api/photoslibrary/v1/photoslibrary.go#L1450)) which returns the album's content in pages.

I'm wondering if my package should wrap this method following all the options. I'm not sure if it will add any value on top of the `SearchMediaItemsRequest` call. **WDYT**?

**Comment by jasondborneman** [comment]
@pacoorozco So you're saying this library already implements SearchMediaItemsRequest? I feel like I must have totally missed that. Any chance you've got an example of using it you could link to? I'm still teaching myself Go and learn best with examples.

Thanks so much for taking the time to look into this!

**Comment by pacoorozco** [comment]
Yes, maybe it's better to allow users to paginate through album's content.

**Comment by pacoorozco** [comment]
@sealbro Sorry, I skip your comment 🤷🏼 I don't know how it happened... anyways... I would say that newer versions are working...
